/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ApiError, Error};
use crate::models;

use reqwest;

/// Retrieves multiple albums by available filters, or without if applicable.
///
/// # Parameters
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
/// * `include` - Allows the client to customize which related resources should be returned. Available options: artists, coverArt, genres, items, owners, providers, similarAlbums (e.g. "artists")
/// * `filter_owners_period_id` - User id (e.g. "123456")
/// * `filter_id` - Album id (e.g. "251380836")
/// * `filter_barcode_id` - Barcode Id (e.g. "196589525444")
pub async fn albums_get(
    configuration: &configuration::Configuration,
    page_cursor: Option<&str>,
    include: Option<Vec<String>>,
    filter_owners_period_id: Option<Vec<String>>,
    filter_id: Option<Vec<String>>,
    filter_barcode_id: Option<Vec<String>>,
) -> Result<models::MultiResource<models::Album>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_page_cursor = page_cursor;
    let p_include = include;
    let p_filter_owners_period_id = filter_owners_period_id;
    let p_filter_id = filter_id;
    let p_filter_barcode_id = filter_barcode_id;

    let uri_str = format!("{}/albums", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = p_filter_owners_period_id {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("filter[owners.id]".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "filter[owners.id]",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = p_filter_id {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("filter[id]".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "filter[id]",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = p_filter_barcode_id {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("filter[barcodeId]".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "filter[barcodeId]",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    configuration.execute_request(req_builder).await
}

/// Deletes existing album.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
pub async fn albums_id_delete(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<(), Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;

    let uri_str = format!(
        "{}/albums/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    configuration.execute_request(req_builder).await
}

/// Retrieves single album by id.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
/// * `include` - Allows the client to customize which related resources should be returned. Available options: artists, coverArt, genres, items, owners, providers, similarAlbums (e.g. "artists")
pub async fn albums_id_get(
    configuration: &configuration::Configuration,
    id: &str,
    include: Option<Vec<String>>,
) -> Result<models::Resource<models::Album>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_include = include;

    let uri_str = format!(
        "{}/albums/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    configuration.execute_request(req_builder).await
}

/// Updates existing album.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
pub async fn albums_id_patch(
    configuration: &configuration::Configuration,
    id: &str,
    album_update_operation_payload: Option<models::AlbumUpdateOperationPayload>,
) -> Result<(), Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_album_update_operation_payload = album_update_operation_payload;

    let uri_str = format!(
        "{}/albums/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    req_builder = req_builder.json(&p_album_update_operation_payload);

    configuration.execute_request(req_builder).await
}

/// Retrieves artists relationship.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn albums_id_relationships_artists_get(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/albums/{id}/relationships/artists",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("include", "artists")]);

    configuration.execute_request(req_builder).await
}

/// Retrieves coverArt relationship.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn albums_id_relationships_cover_art_get(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/albums/{id}/relationships/coverArt",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("include", "coverArt")]);

    configuration.execute_request(req_builder).await
}

/// Updates coverArt relationship.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
pub async fn albums_id_relationships_cover_art_patch(
    configuration: &configuration::Configuration,
    id: &str,
    album_cover_art_relationship_update_operation_payload: Option<
        models::AlbumCoverArtRelationshipUpdateOperationPayload,
    >,
) -> Result<(), Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_album_cover_art_relationship_update_operation_payload =
        album_cover_art_relationship_update_operation_payload;

    let uri_str = format!(
        "{}/albums/{id}/relationships/coverArt",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    req_builder = req_builder.json(&p_album_cover_art_relationship_update_operation_payload);

    configuration.execute_request(req_builder).await
}

/// Retrieves genres relationship.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn albums_id_relationships_genres_get(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/albums/{id}/relationships/genres",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("include", "genres")]);

    configuration.execute_request(req_builder).await
}

/// Retrieves items relationship.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn albums_id_relationships_items_get(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
) -> Result<models::MultiRelationship<models::AlbumsItemsResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/albums/{id}/relationships/items",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("include", "items")]);

    configuration.execute_request(req_builder).await
}

/// Retrieves owners relationship.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn albums_id_relationships_owners_get(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/albums/{id}/relationships/owners",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("include", "owners")]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    configuration.execute_request(req_builder).await
}

/// Retrieves providers relationship.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn albums_id_relationships_providers_get(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/albums/{id}/relationships/providers",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    req_builder = req_builder.query(&[("include", "providers")]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    configuration.execute_request(req_builder).await
}

/// Retrieves similarAlbums relationship.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn albums_id_relationships_similar_albums_get(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/albums/{id}/relationships/similarAlbums",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("include", "similarAlbums")]);

    configuration.execute_request(req_builder).await
}

/// Creates a new album.
///
/// # Parameters
/// * `album_create_operation_payload` - Request body payload for creating a new album
pub async fn albums_post(
    configuration: &configuration::Configuration,
    album_create_operation_payload: Option<models::AlbumCreateOperationPayload>,
) -> Result<models::Resource<models::Album>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_album_create_operation_payload = album_create_operation_payload;

    let uri_str = format!("{}/albums", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.json(&p_album_create_operation_payload);

    configuration.execute_request(req_builder).await
}
