/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ApiError, Error};
use crate::models::*;
use serde::{Deserialize, Serialize};

use reqwest;

/// Retrieves multiple albums by available filters, or without if applicable.
///
/// # Parameters
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
/// * `include` - Allows the client to customize which related resources should be returned. Available options: artists, coverArt, genres, items, owners, providers, similarAlbums (e.g. "artists")
/// * `filter_owners_period_id` - User id (e.g. "123456")
/// * `filter_id` - Album id (e.g. "251380836")
/// * `filter_barcode_id` - Barcode Id (e.g. "196589525444")
pub async fn album_list(
    configuration: &configuration::Configuration,
    page_cursor: Option<&str>,
    include: Option<Vec<String>>,
    filter_owners_period_id: Option<Vec<String>>,
    filter_id: Option<Vec<String>>,
    filter_barcode_id: Option<Vec<String>>,
) -> Result<MultiResource<album::Album>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_page_cursor = page_cursor;
    let p_include = include;
    let p_filter_owners_period_id = filter_owners_period_id;
    let p_filter_id = filter_id;
    let p_filter_barcode_id = filter_barcode_id;

    let uri_str = format!("{}/albums", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include {
        req_builder = req_builder.query(
            &param_value
                .iter()
                .map(|p| ("include".to_owned(), p.to_string()))
                .collect::<Vec<(std::string::String, std::string::String)>>(),
        );
    }
    if let Some(ref param_value) = p_filter_owners_period_id {
        req_builder = req_builder.query(
            &param_value
                .iter()
                .map(|p| ("filter[owners.id]".to_owned(), p.to_string()))
                .collect::<Vec<(std::string::String, std::string::String)>>(),
        );
    }
    if let Some(ref param_value) = p_filter_id {
        req_builder = req_builder.query(
            &param_value
                .iter()
                .map(|p| ("filter[id]".to_owned(), p.to_string()))
                .collect::<Vec<(std::string::String, std::string::String)>>(),
        );
    }
    if let Some(ref param_value) = p_filter_barcode_id {
        req_builder = req_builder.query(
            &param_value
                .iter()
                .map(|p| ("filter[barcodeId]".to_owned(), p.to_string()))
                .collect::<Vec<(std::string::String, std::string::String)>>(),
        );
    }

    configuration.execute_request(req_builder).await
}

/// Retrieves single album by id.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
/// * `include` - Allows the client to customize which related resources should be returned. Available options: artists, coverArt, genres, items, owners, providers, similarAlbums (e.g. "artists")
pub async fn album_get(
    configuration: &configuration::Configuration,
    id: &str,
    include: Option<Vec<String>>,
) -> Result<Resource<album::Album>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_include = include;

    let uri_str = format!(
        "{}/albums/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_include {
        req_builder = req_builder.query(
            &param_value
                .iter()
                .map(|p| ("include".to_owned(), p.to_string()))
                .collect::<Vec<(std::string::String, std::string::String)>>(),
        );
    }

    configuration.execute_request(req_builder).await
}

/// Retrieves artists relationship.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn album_artists(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
) -> Result<MultiRelationship<ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/albums/{id}/relationships/artists",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("include", "artists")]);

    configuration.execute_request(req_builder).await
}

/// Retrieves coverArt relationship.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn album_cover_art(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
) -> Result<MultiRelationship<ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/albums/{id}/relationships/coverArt",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("include", "coverArt")]);

    configuration.execute_request(req_builder).await
}

/// Retrieves items relationship.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn album_items(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
) -> Result<MultiRelationship<ResourceIdentifier<album::AlbumsItemsResourceMeta>>, Error<ApiError>>
{
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/albums/{id}/relationships/items",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("include", "items")]);

    configuration.execute_request(req_builder).await
}

/// Retrieves owners relationship.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn album_owners(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
) -> Result<MultiRelationship<ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/albums/{id}/relationships/owners",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("include", "owners")]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    configuration.execute_request(req_builder).await
}

/// Retrieves providers relationship.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn album_providers(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
) -> Result<MultiRelationship<ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/albums/{id}/relationships/providers",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    req_builder = req_builder.query(&[("include", "providers")]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    configuration.execute_request(req_builder).await
}

/// Retrieves similarAlbums relationship.
///
/// # Parameters
/// * `id` - Album id (e.g. "251380836")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn album_similar_albums(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
) -> Result<MultiRelationship<ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/albums/{id}/relationships/similarAlbums",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("include", "similarAlbums")]);

    configuration.execute_request(req_builder).await
}
