/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ApiError, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`appreciations_post`]
pub type AppreciationsPostError = ApiError;

/// Creates a new appreciation.
pub async fn appreciations_post(
    configuration: &configuration::Configuration,
    appreciations_create_operation_payload: Option<models::AppreciationsCreateOperationPayload>,
) -> Result<models::AppreciationsSingleResourceDataDocument, Error<AppreciationsPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_appreciations_create_operation_payload = appreciations_create_operation_payload;

    let uri_str = format!("{}/appreciations", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.json(&p_appreciations_create_operation_payload);

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AppreciationsSingleResourceDataDocument`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AppreciationsSingleResourceDataDocument`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AppreciationsPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
