/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ApiError, ContentType, Error};
use crate::{apis::ResponseContent, models};
use log::trace;
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// Retrieves multiple artists by available filters, or without if applicable.
///
/// # Parameters
/// * `include` - Allows the client to customize which related resources should be returned. Available options: albums, biography, followers, following, owners, profileArt, radio, roles, similarArtists, trackProviders, tracks, videos (e.g. "albums")
/// * `collapse_by` - Collapse by options for getting artist tracks. Available options: FINGERPRINT, ID. FINGERPRINT option might collapse similar tracks based entry fingerprints while collapsing by ID always returns all available items. (e.g. "FINGERPRINT")
/// * `filter_handle` - Artist handle (e.g. "jayz")
/// * `filter_id` - Artist id (e.g. "1566")
pub async fn artists_get(
    configuration: &configuration::Configuration,
    include: Option<Vec<String>>,
    collapse_by: Option<String>,
    filter_handle: Option<Vec<String>>,
    filter_id: Option<Vec<String>>,
) -> Result<models::MultiResource<models::Artist>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_include = include;
    let p_filter_handle = filter_handle;
    let p_filter_id = filter_id;
    let p_collapse_by = collapse_by;

    let uri_str = format!("{}/artists", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_collapse_by {
        req_builder = req_builder.query(&[("collapseBy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = p_filter_handle {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("filter[handle]".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "filter[handle]",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = p_filter_id {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("filter[id]".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "filter[id]",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MultiResource<models::Artist>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MultiResource<models::Artist>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves single artist by id.
///
/// # Parameters
/// * `id` - Artist id (e.g. "1566")
/// * `include` - Allows the client to customize which related resources should be returned. Available options: albums, biography, followers, following, owners, profileArt, radio, roles, similarArtists, trackProviders, tracks, videos (e.g. "albums")
/// * `collapse_by` - Collapse by options for getting artist tracks. Available options: FINGERPRINT, ID. FINGERPRINT option might collapse similar tracks based entry fingerprints while collapsing by ID always returns all available items. (e.g. "FINGERPRINT")
pub async fn artists_id_get(
    configuration: &configuration::Configuration,
    id: &str,
    include: Option<Vec<String>>,
    collapse_by: Option<String>,
) -> Result<models::Resource<models::Artist>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_include = include;
    let p_collapse_by = collapse_by;

    let uri_str = format!(
        "{}/artists/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_collapse_by {
        req_builder = req_builder.query(&[("collapseBy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Resource<models::Artist>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Resource<models::Artist>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Updates existing artist.
///
/// # Parameters
/// * `id` - Artist id (e.g. "1566")
pub async fn artists_id_patch(
    configuration: &configuration::Configuration,
    id: &str,
    artist_update_body: Option<models::ArtistUpdateBody>,
) -> Result<(), Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_artist_update_body = artist_update_body;

    let uri_str = format!(
        "{}/artists/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    req_builder = req_builder.json(&p_artist_update_body);

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves albums relationship.
///
/// # Parameters
/// * `id` - Artist id (e.g. "1566")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
/// * `include` - Allows the client to customize which related resources should be returned. Available options: albums (e.g. "albums")
pub async fn artists_id_relationships_albums_get(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
    include: Option<Vec<String>>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;
    let p_include = include;

    let uri_str = format!(
        "{}/artists/{id}/relationships/albums",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves biography relationship.
///
/// # Parameters
/// * `id` - Artist id (e.g. "1566")
/// * `include` - Allows the client to customize which related resources should be returned. Available options: biography (e.g. "biography")
pub async fn artists_id_relationships_biography_get(
    configuration: &configuration::Configuration,
    id: &str,
    include: Option<Vec<String>>,
) -> Result<models::Relationship, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_include = include;

    let uri_str = format!(
        "{}/artists/{id}/relationships/biography",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Relationship`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Relationship`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves followers relationship.
pub async fn artists_id_relationships_followers_get(
    configuration: &configuration::Configuration,
    id: &str,
    viewer_context: Option<&str>,
    page_cursor: Option<&str>,
    include: Option<Vec<String>>,
) -> Result<models::MultiRelationship<models::ArtistsFollowersResourceIdentifier>, Error<ApiError>>
{
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_viewer_context = viewer_context;
    let p_page_cursor = page_cursor;
    let p_include = include;

    let uri_str = format!(
        "{}/artists/{id}/relationships/followers",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_viewer_context {
        req_builder = req_builder.query(&[("viewerContext", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MultiRelationship<models::ArtistsFollowersResourceIdentifier>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MultiRelationship<models::ArtistsFollowersResourceIdentifier>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Deletes item(s) from following relationship.
pub async fn artists_id_relationships_following_delete(
    configuration: &configuration::Configuration,
    id: &str,
    artist_following_relationship_remove_operation_payload: Option<
        models::ArtistFollowingRelationshipRemoveOperationPayload,
    >,
) -> Result<(), Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_artist_following_relationship_remove_operation_payload =
        artist_following_relationship_remove_operation_payload;

    let uri_str = format!(
        "{}/artists/{id}/relationships/following",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    req_builder = req_builder.json(&p_artist_following_relationship_remove_operation_payload);

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves following relationship.
pub async fn artists_id_relationships_following_get(
    configuration: &configuration::Configuration,
    id: &str,
    viewer_context: Option<&str>,
    page_cursor: Option<&str>,
    include: Option<Vec<String>>,
) -> Result<models::MultiRelationship<models::ArtistsFollowingResourceIdentifier>, Error<ApiError>>
{
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_viewer_context = viewer_context;
    let p_page_cursor = page_cursor;
    let p_include = include;

    let uri_str = format!(
        "{}/artists/{id}/relationships/following",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_viewer_context {
        req_builder = req_builder.query(&[("viewerContext", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MultiRelationship<models::ArtistsFollowingResourceIdentifier>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MultiRelationship<models::ArtistsFollowingResourceIdentifier>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Adds item(s) to following relationship.
pub async fn artists_id_relationships_following_post(
    configuration: &configuration::Configuration,
    id: &str,
    artist_following_relationship_add_operation_payload: Option<
        models::ArtistFollowingRelationshipAddOperationPayload,
    >,
) -> Result<(), Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_artist_following_relationship_add_operation_payload =
        artist_following_relationship_add_operation_payload;

    let uri_str = format!(
        "{}/artists/{id}/relationships/following",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    req_builder = req_builder.json(&p_artist_following_relationship_add_operation_payload);

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves owners relationship.
pub async fn artists_id_relationships_owners_get(
    configuration: &configuration::Configuration,
    id: &str,
    include: Option<Vec<String>>,
    page_cursor: Option<&str>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_include = include;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/artists/{id}/relationships/owners",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves profileArt relationship.
pub async fn artists_id_relationships_profile_art_get(
    configuration: &configuration::Configuration,
    id: &str,
    include: Option<Vec<String>>,
    page_cursor: Option<&str>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_include = include;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/artists/{id}/relationships/profileArt",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Updates profileArt relationship.
pub async fn artists_id_relationships_profile_art_patch(
    configuration: &configuration::Configuration,
    id: &str,
    artist_profile_art_relationship_update_operation_payload: Option<
        models::ArtistProfileArtRelationshipUpdateOperationPayload,
    >,
) -> Result<(), Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_artist_profile_art_relationship_update_operation_payload =
        artist_profile_art_relationship_update_operation_payload;

    let uri_str = format!(
        "{}/artists/{id}/relationships/profileArt",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    req_builder = req_builder.json(&p_artist_profile_art_relationship_update_operation_payload);

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves radio relationship.
pub async fn artists_id_relationships_radio_get(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
    include: Option<Vec<String>>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;
    let p_include = include;

    let uri_str = format!(
        "{}/artists/{id}/relationships/radio",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves roles relationship.
pub async fn artists_id_relationships_roles_get(
    configuration: &configuration::Configuration,
    id: &str,
    include: Option<Vec<String>>,
    page_cursor: Option<&str>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_include = include;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/artists/{id}/relationships/roles",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves similarArtists relationship.
pub async fn artists_id_relationships_similar_artists_get(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
    include: Option<Vec<String>>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;
    let p_include = include;

    let uri_str = format!(
        "{}/artists/{id}/relationships/similarArtists",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves trackProviders relationship.
pub async fn artists_id_relationships_track_providers_get(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
    include: Option<Vec<String>>,
) -> Result<
    models::MultiRelationship<models::ArtistsTrackProvidersResourceIdentifier>,
    Error<ApiError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;
    let p_include = include;

    let uri_str = format!(
        "{}/artists/{id}/relationships/trackProviders",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MultiRelationship<models::ArtistsTrackProvidersResourceIdentifier>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MultiRelationship<models::ArtistsTrackProvidersResourceIdentifier>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves tracks relationship.
pub async fn artists_id_relationships_tracks_get(
    configuration: &configuration::Configuration,
    id: &str,
    collapse_by: &str,
    page_cursor: Option<&str>,
    include: Option<Vec<String>>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_collapse_by = collapse_by;
    let p_page_cursor = page_cursor;
    let p_include = include;

    let uri_str = format!(
        "{}/artists/{id}/relationships/tracks",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    req_builder = req_builder.query(&[("collapseBy", &p_collapse_by.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves videos relationship.
pub async fn artists_id_relationships_videos_get(
    configuration: &configuration::Configuration,
    id: &str,
    page_cursor: Option<&str>,
    include: Option<Vec<String>>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_page_cursor = page_cursor;
    let p_include = include;

    let uri_str = format!(
        "{}/artists/{id}/relationships/videos",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Creates a new artist.
pub async fn artists_post(
    configuration: &configuration::Configuration,
    artist_create_operation_payload: Option<models::ArtistCreateOperationPayload>,
) -> Result<models::Resource<models::Artist>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_artist_create_operation_payload = artist_create_operation_payload;

    let uri_str = format!("{}/artists", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.json(&p_artist_create_operation_payload);

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Resource<models::Artist>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Resource<models::Artist>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
