/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use log::{debug, info};

#[derive(Debug, Clone)]
pub struct Configuration {
    pub base_path: String,
    pub user_agent: Option<String>,
    pub client: reqwest::Client,
    pub basic_auth: Option<BasicAuth>,
    pub oauth_access_token: Option<String>,
    pub bearer_access_token: Option<String>,
    pub api_key: Option<ApiKey>,
    pub country_code: String,
}

pub type BasicAuth = (String, Option<String>);

#[derive(Debug, Clone)]
pub struct ApiKey {
    pub prefix: Option<String>,
    pub key: String,
}

impl Configuration {
    pub fn new() -> Configuration {
        Configuration::default()
    }

    /// Execute HTTP request with comprehensive logging and authentication
    /// This centralizes all request execution and adds logging for headers, url, method, and response code
    /// Also applies authentication headers (bearer token, user agent, etc.) automatically
    pub async fn execute_request(
        &self,
        mut req_builder: reqwest::RequestBuilder,
    ) -> Result<reqwest::Response, reqwest::Error> {
        // Apply authentication and headers before building the request
        if let Some(ref user_agent) = self.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // Apply bearer token authentication (prioritize bearer_access_token over oauth_access_token)
        if let Some(ref token) = self.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        } else if let Some(ref token) = self.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        }

        // Apply basic auth if configured
        if let Some(ref basic_auth) = self.basic_auth {
            req_builder = req_builder.basic_auth(&basic_auth.0, basic_auth.1.as_ref());
        }

        // Apply API key if configured (typically as a header)
        if let Some(ref api_key) = self.api_key {
            let header_name = match &api_key.prefix {
                Some(prefix) => format!("{} {}", prefix, api_key.key),
                None => api_key.key.clone(),
            };
            req_builder = req_builder.header("Authorization", header_name);
        }

        let req = req_builder.build()?;

        let method = req.method().clone();
        let url = req.url().clone();
        let headers = req.headers().clone();

        debug!("HTTP Request - Method: {}, URL: {}", method, url);

        let response = self.client.execute(req).await?;

        let status = response.status();
        let response_headers = response.headers().clone();

        info!(
            "HTTP Response - Method: {}, URL: {}, Status: {}",
            method, url, status
        );
        debug!("HTTP Response Headers: {:?}", response_headers);

        Ok(response)
    }
}

impl Default for Configuration {
    fn default() -> Self {
        Configuration {
            base_path: "https://openapi.tidal.com/v2".to_owned(),
            user_agent: Some("OpenAPI-Generator/0.1.76/rust".to_owned()),
            client: reqwest::Client::new(),
            basic_auth: None,
            oauth_access_token: None,
            bearer_access_token: None,
            api_key: None,
            country_code: "US".to_owned(),
        }
    }
}
