/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ApiError, Error};
use crate::models;

use reqwest;

/// Retrieves multiple lyrics by available filters, or without if applicable.
///
/// # Parameters
/// * `include` - Allows the client to customize which related resources should be returned. Available options: owners, track (e.g. "owners")
/// * `filter_id` - Lyrics Id (e.g. "nejMcAhh5N8S3EQ4LaqysVdI0cZZ")
pub async fn lyrics_get(
    configuration: &configuration::Configuration,
    include: Option<Vec<String>>,
    filter_id: Option<Vec<String>>,
) -> Result<models::MultiResource<models::Lyrics>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_include = include;
    let p_filter_id = filter_id;

    let uri_str = format!("{}/lyrics", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = p_filter_id {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("filter[id]".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "filter[id]",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    configuration.execute_request(req_builder).await
}

/// Retrieves single lyric by id.
///
/// # Parameters
/// * `id` - Lyrics Id (e.g. "nejMcAhh5N8S3EQ4LaqysVdI0cZZ")
/// * `include` - Allows the client to customize which related resources should be returned. Available options: owners, track (e.g. "owners")
pub async fn lyrics_id_get(
    configuration: &configuration::Configuration,
    id: &str,
    include: Option<Vec<String>>,
) -> Result<models::Resource<models::Lyrics>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_include = include;

    let uri_str = format!(
        "{}/lyrics/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    configuration.execute_request(req_builder).await
}

/// Updates existing lyric.
pub async fn lyrics_id_patch(
    configuration: &configuration::Configuration,
    id: &str,
    lyrics_update_operation_payload: Option<models::LyricsUpdateOperationPayload>,
) -> Result<(), Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_lyrics_update_operation_payload = lyrics_update_operation_payload;

    let uri_str = format!(
        "{}/lyrics/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    req_builder = req_builder.json(&p_lyrics_update_operation_payload);

    configuration.execute_request(req_builder).await
}

/// Retrieves owners relationship.
pub async fn lyrics_id_relationships_owners_get(
    configuration: &configuration::Configuration,
    id: &str,
    include: Option<Vec<String>>,
    page_cursor: Option<&str>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_include = include;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/lyrics/{id}/relationships/owners",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    configuration.execute_request(req_builder).await
}

/// Retrieves track relationship.
pub async fn lyrics_id_relationships_track_get(
    configuration: &configuration::Configuration,
    id: &str,
    include: Option<Vec<String>>,
) -> Result<models::Relationship, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_include = include;

    let uri_str = format!(
        "{}/lyrics/{id}/relationships/track",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    configuration.execute_request(req_builder).await
}

/// Creates a new lyric.
///
/// # Parameters
/// * `lyrics_create_operation_payload` - Request body payload for creating a new lyric
pub async fn lyrics_post(
    configuration: &configuration::Configuration,
    lyrics_create_operation_payload: Option<models::LyricsCreateOperationPayload>,
) -> Result<models::Resource<models::Lyrics>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_lyrics_create_operation_payload = lyrics_create_operation_payload;

    let uri_str = format!("{}/lyrics", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.json(&p_lyrics_create_operation_payload);

    configuration.execute_request(req_builder).await
}
