/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ApiError, Error};
use crate::models::*;

use reqwest;

/// Retrieves single searchSuggestion by id.
pub async fn search_suggestion_get(
    configuration: &configuration::TidalClient,
    id: &str,
    explicit_filter: Option<&str>,
    include: Option<Vec<String>>,
) -> Result<Resource<search_suggestions::SearchSuggestion>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_explicit_filter = explicit_filter;
    let p_include = include;

    let uri_str = format!(
        "{}/searchSuggestions/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_explicit_filter {
        req_builder = req_builder.query(&[("explicitFilter", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include {
        req_builder = req_builder.query(
            &param_value
                .iter()
                .map(|p| ("include".to_owned(), p.to_string()))
                .collect::<Vec<(std::string::String, std::string::String)>>(),
        );
    }

    configuration.execute_request(req_builder).await
}

/// Retrieves directHits relationship.
///
/// # Parameters
/// * `id` - Search suggestion id
/// * `explicit_filter` - Explicit filter (e.g. "INCLUDE/EXCLUDE")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn search_suggestion_direct_hits(
    configuration: &configuration::TidalClient,
    id: &str,
    explicit_filter: Option<&str>,
    page_cursor: Option<&str>,
) -> Result<MultiRelationship<ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_explicit_filter = explicit_filter;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/searchSuggestions/{id}/relationships/directHits",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    if let Some(ref param_value) = p_explicit_filter {
        req_builder = req_builder.query(&[("explicitFilter", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("include", "directHits")]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    configuration.execute_request(req_builder).await
}
