/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType, StandardApiError};


/// struct for typed errors of method [`track_source_files_get`]
pub type TrackSourceFilesGetError = StandardApiError;

/// struct for typed errors of method [`track_source_files_id_get`]
pub type TrackSourceFilesIdGetError = StandardApiError;

/// struct for typed errors of method [`track_source_files_id_relationships_owners_get`]
pub type TrackSourceFilesIdRelationshipsOwnersGetError = StandardApiError;

/// struct for typed errors of method [`track_source_files_post`]
pub type TrackSourceFilesPostError = StandardApiError;


/// Retrieves multiple trackSourceFiles by available filters, or without if applicable.
pub async fn track_source_files_get(configuration: &configuration::Configuration, include: Option<Vec<String>>, filter_id: Option<Vec<String>>) -> Result<models::TrackSourceFilesMultiResourceDataDocument, Error<TrackSourceFilesGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_include = include;
    let p_filter_id = filter_id;

    let uri_str = format!("{}/trackSourceFiles", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("include".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("include", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_filter_id {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("filter[id]".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("filter[id]", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TrackSourceFilesMultiResourceDataDocument`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TrackSourceFilesMultiResourceDataDocument`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TrackSourceFilesGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves single trackSourceFile by id.
pub async fn track_source_files_id_get(configuration: &configuration::Configuration, id: &str, include: Option<Vec<String>>) -> Result<models::TrackSourceFilesSingleResourceDataDocument, Error<TrackSourceFilesIdGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_include = include;

    let uri_str = format!("{}/trackSourceFiles/{id}", configuration.base_path, id=crate::apis::urlencode(p_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("include".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("include", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TrackSourceFilesSingleResourceDataDocument`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TrackSourceFilesSingleResourceDataDocument`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TrackSourceFilesIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieves owners relationship.
pub async fn track_source_files_id_relationships_owners_get(configuration: &configuration::Configuration, id: &str, include: Option<Vec<String>>, page_cursor: Option<&str>) -> Result<models::TrackSourceFilesMultiRelationshipDataDocument, Error<TrackSourceFilesIdRelationshipsOwnersGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_include = include;
    let p_page_cursor = page_cursor;

    let uri_str = format!("{}/trackSourceFiles/{id}/relationships/owners", configuration.base_path, id=crate::apis::urlencode(p_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("include".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("include", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TrackSourceFilesMultiRelationshipDataDocument`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TrackSourceFilesMultiRelationshipDataDocument`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TrackSourceFilesIdRelationshipsOwnersGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Creates a new trackSourceFile.
pub async fn track_source_files_post(configuration: &configuration::Configuration, track_source_file_create_operation_payload: Option<models::TrackSourceFileCreateOperationPayload>) -> Result<models::TrackSourceFilesSingleResourceDataDocument, Error<TrackSourceFilesPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_track_source_file_create_operation_payload = track_source_file_create_operation_payload;

    let uri_str = format!("{}/trackSourceFiles", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.json(&p_track_source_file_create_operation_payload);

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TrackSourceFilesSingleResourceDataDocument`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TrackSourceFilesSingleResourceDataDocument`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TrackSourceFilesPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

