/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ApiError, Error};
use crate::models;
use reqwest;

/// Retrieves current user's user(s).
///
/// # Parameters
/// This endpoint takes no parameters.
pub async fn users_me_get(
    configuration: &configuration::Configuration,
) -> Result<models::Resource<models::User>, Error<ApiError>> {
    let uri_str = format!("{}/users/me", configuration.base_path);
    let req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    configuration.execute_request(req_builder).await
}
