/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ApiError, ContentType, Error};
use crate::{apis::ResponseContent, models};
use log::trace;
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// Retrieves single userRecommendation by id.
///
/// # Parameters
/// * `id` - User id (e.g. "123456")
/// * `locale` - BCP47 locale code (e.g. "en-US")
/// * `include` - Allows the client to customize which related resources should be returned. Available options: discoveryMixes, myMixes, newArrivalMixes (e.g. "discoveryMixes")
pub async fn user_recommendations_id_get(
    configuration: &configuration::Configuration,
    id: &str,
    locale: &str,
    include: Option<Vec<String>>,
) -> Result<models::Resource<models::UserRecommendation>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_locale = locale;
    let p_include = include;

    let uri_str = format!(
        "{}/userRecommendations/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    req_builder = req_builder.query(&[("locale", &p_locale.to_string())]);
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Resource<models::UserRecommendation>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Resource<models::UserRecommendation>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves discoveryMixes relationship.
pub async fn user_recommendations_id_relationships_discovery_mixes_get(
    configuration: &configuration::Configuration,
    id: &str,
    locale: &str,
    include: Option<Vec<String>>,
    page_cursor: Option<&str>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_locale = locale;
    let p_include = include;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/userRecommendations/{id}/relationships/discoveryMixes",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    req_builder = req_builder.query(&[("locale", &p_locale.to_string())]);
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves myMixes relationship.
pub async fn user_recommendations_id_relationships_my_mixes_get(
    configuration: &configuration::Configuration,
    id: &str,
    locale: &str,
    include: Option<Vec<String>>,
    page_cursor: Option<&str>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_locale = locale;
    let p_include = include;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/userRecommendations/{id}/relationships/myMixes",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    req_builder = req_builder.query(&[("locale", &p_locale.to_string())]);
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves newArrivalMixes relationship.
pub async fn user_recommendations_id_relationships_new_arrival_mixes_get(
    configuration: &configuration::Configuration,
    id: &str,
    locale: &str,
    include: Option<Vec<String>>,
    page_cursor: Option<&str>,
) -> Result<models::MultiRelationship<models::ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_locale = locale;
    let p_include = include;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/userRecommendations/{id}/relationships/newArrivalMixes",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    req_builder = req_builder.query(&[("locale", &p_locale.to_string())]);
    if let Some(ref param_value) = p_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("include".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "include",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    let resp = configuration.execute_request(req_builder).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MultiRelationship<models::ResourceIdentifier>`")))),
        }
    } else {
        let content = resp.text().await?;
        trace!("Response content: {}", content);
        let entity: Option<ApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
