/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ApiError, Error};
use crate::models::*;

use reqwest;

/// Retrieves single userRecommendation by id.
///
/// # Parameters
/// * `id` - User id (e.g. "123456")
/// * `locale` - BCP47 locale code (e.g. "en-US")
/// * `include` - Allows the client to customize which related resources should be returned. Available options: discoveryMixes, myMixes, newArrivalMixes (e.g. "discoveryMixes")
pub async fn user_recommendation_get(
    configuration: &configuration::TidalClient,
    id: &str,
    locale: &str,
    include: Option<Vec<String>>,
) -> Result<Resource<user_recommendation::UserRecommendation>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_locale = locale;
    let p_include = include;

    let uri_str = format!(
        "{}/userRecommendations/{id}",
        configuration.base_path_api,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    req_builder = req_builder.query(&[("locale", &p_locale.to_string())]);
    if let Some(ref param_value) = p_include {
        req_builder = req_builder.query(
            &param_value
                .iter()
                .map(|p| ("include".to_owned(), p.to_string()))
                .collect::<Vec<(std::string::String, std::string::String)>>(),
        );
    }

    configuration.execute_request(req_builder).await
}

/// Retrieves discoveryMixes relationship.
///
/// # Parameters
/// * `id` - User id (e.g. "123456")
/// * `locale` - BCP47 locale code (e.g. "en-US")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn user_recommendation_discovery_mixes(
    configuration: &configuration::TidalClient,
    id: &str,
    locale: &str,
    page_cursor: Option<&str>,
) -> Result<MultiRelationship<ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_locale = locale;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/userRecommendations/{id}/relationships/discoveryMixes",
        configuration.base_path_api,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    req_builder = req_builder.query(&[("locale", &p_locale.to_string())]);
    req_builder = req_builder.query(&[("include", "discoveryMixes")]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    configuration.execute_request(req_builder).await
}

/// Retrieves myMixes relationship.
///
/// # Parameters
/// * `id` - User id (e.g. "123456")
/// * `locale` - BCP47 locale code (e.g. "en-US")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn user_recommendation_my_mixes(
    configuration: &configuration::TidalClient,
    id: &str,
    locale: &str,
    page_cursor: Option<&str>,
) -> Result<MultiRelationship<ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_locale = locale;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/userRecommendations/{id}/relationships/myMixes",
        configuration.base_path_api,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    req_builder = req_builder.query(&[("locale", &p_locale.to_string())]);
    req_builder = req_builder.query(&[("include", "myMixes")]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    configuration.execute_request(req_builder).await
}

/// Retrieves newArrivalMixes relationship.
///
/// # Parameters
/// * `id` - User id (e.g. "123456")
/// * `locale` - BCP47 locale code (e.g. "en-US")
/// * `page_cursor` - Server-generated cursor value pointing a certain page of items. Optional, targets first page if not specified
pub async fn user_recommendation_new_arrival_mixes(
    configuration: &configuration::TidalClient,
    id: &str,
    locale: &str,
    page_cursor: Option<&str>,
) -> Result<MultiRelationship<ResourceIdentifier>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_locale = locale;
    let p_page_cursor = page_cursor;

    let uri_str = format!(
        "{}/userRecommendations/{id}/relationships/newArrivalMixes",
        configuration.base_path_api,
        id = crate::apis::urlencode(p_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("countryCode", &configuration.country_code.to_string())]);
    req_builder = req_builder.query(&[("locale", &p_locale.to_string())]);
    req_builder = req_builder.query(&[("include", "newArrivalMixes")]);
    if let Some(ref param_value) = p_page_cursor {
        req_builder = req_builder.query(&[("page[cursor]", &param_value.to_string())]);
    }

    configuration.execute_request(req_builder).await
}
