/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ApiError, Error};
use crate::models;

use reqwest;

/// Retrieves single userEntitlement by id.
///
/// # Parameters
/// * `id` - User id (e.g. "123456")
pub async fn user_entitlement_get(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<models::Resource<models::UserEntitlement>, Error<ApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;

    let uri_str = format!(
        "{}/userEntitlements/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(p_id)
    );
    let req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    configuration.execute_request(req_builder).await
}
