/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlbumsRelationships {
    #[serde(rename = "artists")]
    pub artists: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "coverArt")]
    pub cover_art: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "genres")]
    pub genres: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "items")]
    pub items: models::MultiRelationship<
        models::ResourceIdentifier<crate::apis::albums_api::AlbumsItemsResourceMeta>,
    >,
    #[serde(rename = "owners")]
    pub owners: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "providers")]
    pub providers: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "similarAlbums")]
    pub similar_albums: models::MultiRelationship<models::ResourceIdentifier>,
}

impl AlbumsRelationships {
    pub fn new(
        artists: models::MultiRelationship<models::ResourceIdentifier>,
        cover_art: models::MultiRelationship<models::ResourceIdentifier>,
        genres: models::MultiRelationship<models::ResourceIdentifier>,
        items: models::MultiRelationship<
            models::ResourceIdentifier<crate::apis::albums_api::AlbumsItemsResourceMeta>,
        >,
        owners: models::MultiRelationship<models::ResourceIdentifier>,
        providers: models::MultiRelationship<models::ResourceIdentifier>,
        similar_albums: models::MultiRelationship<models::ResourceIdentifier>,
    ) -> AlbumsRelationships {
        AlbumsRelationships {
            artists,
            cover_art,
            genres,
            items,
            owners,
            providers,
            similar_albums,
        }
    }
}
