/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtistCreateOperationPayload {
    #[serde(rename = "data")]
    pub data: models::ArtistCreateOperationPayloadData,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<models::ArtistCreateOperationMeta>,
}

impl ArtistCreateOperationPayload {
    pub fn new(data: models::ArtistCreateOperationPayloadData) -> ArtistCreateOperationPayload {
        ArtistCreateOperationPayload {
            data,
            meta: None,
        }
    }
}

