/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtistClaimsRelationships {
    #[serde(rename = "acceptedArtists")]
    pub accepted_artists: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "owners")]
    pub owners: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "recommendedArtists")]
    pub recommended_artists: models::MultiRelationship<models::ResourceIdentifier>,
}

impl ArtistClaimsRelationships {
    pub fn new(
        accepted_artists: models::MultiRelationship<models::ResourceIdentifier>,
        owners: models::MultiRelationship<models::ResourceIdentifier>,
        recommended_artists: models::MultiRelationship<models::ResourceIdentifier>,
    ) -> ArtistClaimsRelationships {
        ArtistClaimsRelationships {
            accepted_artists,
            owners,
            recommended_artists,
        }
    }
}
