/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtistCreateOperationPayloadDataAttributes {
    #[serde(rename = "handle", skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
}

impl ArtistCreateOperationPayloadDataAttributes {
    pub fn new(name: String) -> ArtistCreateOperationPayloadDataAttributes {
        ArtistCreateOperationPayloadDataAttributes {
            handle: None,
            name,
        }
    }
}

