/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtistBiographiesAttributes {
    /// Boolean to indicate if the biography is editable (source = tidal or artist)
    #[serde(rename = "editable")]
    pub editable: bool,
    /// Artist biography
    #[serde(rename = "text")]
    pub text: String,
}

impl ArtistBiographiesAttributes {
    pub fn new(editable: bool, text: String) -> ArtistBiographiesAttributes {
        ArtistBiographiesAttributes { editable, text }
    }
}
