/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtistUpdateBodyDataAttributes {
    #[serde(
        rename = "contributionsEnabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub contributions_enabled: Option<bool>,
    #[serde(
        rename = "contributionsSalesPitch",
        skip_serializing_if = "Option::is_none"
    )]
    pub contributions_sales_pitch: Option<String>,
    #[serde(rename = "externalLinks", skip_serializing_if = "Option::is_none")]
    pub external_links: Option<Vec<models::ExternalLinkPayload>>,
    #[serde(rename = "handle", skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ArtistUpdateBodyDataAttributes {
    pub fn new() -> ArtistUpdateBodyDataAttributes {
        ArtistUpdateBodyDataAttributes {
            contributions_enabled: None,
            contributions_sales_pitch: None,
            external_links: None,
            handle: None,
            name: None,
        }
    }
}
