/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ArtistsFollowersResourceMetaViewerContext : Optional context about the relationship
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtistsFollowersResourceMetaViewerContext {
    /// Boolean to indicate if the artist is following my artist
    #[serde(rename = "followsMyArtist", skip_serializing_if = "Option::is_none")]
    pub follows_my_artist: Option<bool>,
    /// Boolean to indicate if my artist is following the artist
    #[serde(rename = "myArtistFollows", skip_serializing_if = "Option::is_none")]
    pub my_artist_follows: Option<bool>,
}

impl ArtistsFollowersResourceMetaViewerContext {
    /// Optional context about the relationship
    pub fn new() -> ArtistsFollowersResourceMetaViewerContext {
        ArtistsFollowersResourceMetaViewerContext {
            follows_my_artist: None,
            my_artist_follows: None,
        }
    }
}
