/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtworksMultiResourceDataDocument {
    #[serde(rename = "data")]
    pub data: Vec<models::Artwork>,
    #[serde(rename = "included", skip_serializing_if = "Option::is_none")]
    pub included: Option<Vec<models::IncludedInner>>,
    #[serde(rename = "links")]
    pub links: models::Links,
}

impl ArtworksMultiResourceDataDocument {
    pub fn new(
        data: Vec<models::Artwork>,
        links: models::Links,
    ) -> ArtworksMultiResourceDataDocument {
        ArtworksMultiResourceDataDocument {
            data,
            included: None,
            links,
        }
    }
}
