/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ArtworkFileMeta : Metadata about an artwork file
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtworkFileMeta {
    /// Height (in pixels)
    #[serde(rename = "height")]
    pub height: i32,
    /// Width (in pixels)
    #[serde(rename = "width")]
    pub width: i32,
}

impl ArtworkFileMeta {
    /// Metadata about an artwork file
    pub fn new(height: i32, width: i32) -> ArtworkFileMeta {
        ArtworkFileMeta {
            height,
            width,
        }
    }
}

