/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AudioNormalizationData : Track normalization data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AudioNormalization {
    #[serde(rename = "peakAmplitude", skip_serializing_if = "Option::is_none")]
    pub peak_amplitude: Option<f32>,
    #[serde(rename = "replayGain", skip_serializing_if = "Option::is_none")]
    pub replay_gain: Option<f32>,
}

impl AudioNormalization {
    /// Track normalization data
    pub fn new() -> AudioNormalization {
        AudioNormalization {
            peak_amplitude: None,
            replay_gain: None,
        }
    }
}
