/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Copyright : Copyright information
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Copyright {
    #[serde(rename = "text")]
    pub text: String,
}

impl Copyright {
    /// Copyright information
    pub fn new(text: String) -> Copyright {
        Copyright { text }
    }
}
