/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DrmData : DRM data. Absence implies no DRM.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DrmData {
    #[serde(rename = "certificateUrl", skip_serializing_if = "Option::is_none")]
    pub certificate_url: Option<String>,
    #[serde(rename = "drmSystem", skip_serializing_if = "Option::is_none")]
    pub drm_system: Option<DrmSystemFalse>,
    #[serde(rename = "licenseUrl", skip_serializing_if = "Option::is_none")]
    pub license_url: Option<String>,
}

impl DrmData {
    /// DRM data. Absence implies no DRM.
    pub fn new() -> DrmData {
        DrmData {
            certificate_url: None,
            drm_system: None,
            license_url: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DrmSystemFalse {
    #[serde(rename = "FAIRPLAY")]
    Fairplay,
    #[serde(rename = "WIDEVINE")]
    Widevine,
}

impl Default for DrmSystemFalse {
    fn default() -> DrmSystemFalse {
        Self::Fairplay
    }
}

