/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileStatus : File status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileStatus {
    /// Moderation status for file
    #[serde(rename = "moderationFileStatus")]
    pub moderation_file_status: ModerationFileStatusFalse,
    /// Technical status for file
    #[serde(rename = "technicalFileStatus")]
    pub technical_file_status: TechnicalFileStatusFalse,
}

impl FileStatus {
    /// File status
    pub fn new(
        moderation_file_status: ModerationFileStatusFalse,
        technical_file_status: TechnicalFileStatusFalse,
    ) -> FileStatus {
        FileStatus {
            moderation_file_status,
            technical_file_status,
        }
    }
}
/// Moderation status for file
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ModerationFileStatusFalse {
    #[serde(rename = "NOT_MODERATED")]
    NotModerated,
    #[serde(rename = "SCANNING")]
    Scanning,
    #[serde(rename = "FLAGGED")]
    Flagged,
    #[serde(rename = "TAKEN_DOWN")]
    TakenDown,
    #[serde(rename = "OK")]
    Ok,
    #[serde(rename = "ERROR")]
    Error,
}

impl Default for ModerationFileStatusFalse {
    fn default() -> ModerationFileStatusFalse {
        Self::NotModerated
    }
}
/// Technical status for file
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TechnicalFileStatusFalse {
    #[serde(rename = "UPLOAD_REQUESTED")]
    UploadRequested,
    #[serde(rename = "PROCESSING")]
    Processing,
    #[serde(rename = "OK")]
    Ok,
    #[serde(rename = "ERROR")]
    Error,
}

impl Default for TechnicalFileStatusFalse {
    fn default() -> TechnicalFileStatusFalse {
        Self::UploadRequested
    }
}
