/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenresAttributes {
    /// Genre name
    #[serde(rename = "genreName")]
    pub genre_name: String,
}

impl GenresAttributes {
    pub fn new(genre_name: String) -> GenresAttributes {
        GenresAttributes { genre_name }
    }
}
