mod albums_relationships;
pub use self::albums_relationships::AlbumsRelationships;
mod album;
pub use self::album::{Album, AlbumAttributes};
mod appreciations_create_operation_meta;
pub use self::appreciations_create_operation_meta::AppreciationsCreateOperationMeta;
mod appreciation;
pub use self::appreciation::{Appreciation, AppreciationAttributes};
mod artist_biographies_relationships;
pub use self::artist_biographies_relationships::ArtistBiographiesRelationships;
mod artist_biography;
pub use self::artist_biography::{ArtistBiography, ArtistBiographyAttributes};
mod artist_create_operation_meta;
pub use self::artist_create_operation_meta::ArtistCreateOperationMeta;
mod artist_role;
pub use self::artist_role::{ArtistRole, ArtistRoleAttributes};
mod artists_followers_resource_meta_viewer_context;
pub use self::artists_followers_resource_meta_viewer_context::ArtistsFollowersResourceMetaViewerContext;
mod artists_relationships;
pub use self::artists_relationships::ArtistsRelationships;
mod artist;
pub use self::artist::{Artist, ArtistAttributes};
mod artwork_file;
pub use self::artwork_file::ArtworkFile;
mod artwork_file_meta;
pub use self::artwork_file_meta::ArtworkFileMeta;
mod artwork_source_file;
pub use self::artwork_source_file::ArtworkSourceFile;
mod artworks_relationships;
pub use self::artworks_relationships::ArtworksRelationships;
mod artwork;
pub use self::artwork::{Artwork, ArtworkAttributes};
mod audio_normalization_data;
pub use self::audio_normalization_data::AudioNormalizationData;
mod barcode_id;
pub use self::barcode_id::BarcodeId;
mod copyright;
pub use self::copyright::Copyright;
mod drm_data;
pub use self::drm_data::DrmData;
mod error_object;
pub use self::error_object::ErrorObject;
mod error_object_source;
pub use self::error_object_source::ErrorObjectSource;
mod errors_document;
pub use self::errors_document::ErrorsDocument;
mod external_link;
pub use self::external_link::ExternalLink;
mod external_link_meta;
pub use self::external_link_meta::ExternalLinkMeta;
mod external_link_payload;
pub use self::external_link_payload::ExternalLinkPayload;
mod file_status;
pub use self::file_status::FileStatus;
mod file_upload_link;
pub use self::file_upload_link::FileUploadLink;
mod file_upload_link_meta;
pub use self::file_upload_link_meta::FileUploadLinkMeta;
mod genre;
pub use self::genre::{Genre, GenreAttributes};
mod links;
pub use self::links::Links;
mod links_meta;
pub use self::links_meta::LinksMeta;
mod lyrics_relationships;
pub use self::lyrics_relationships::LyricsRelationships;
mod lyrics;
pub use self::lyrics::{Lyrics, LyricsAttributes};
mod playlist_create_operation_payload_data;
pub use self::playlist_create_operation_payload_data::CreatePlaylist;
mod playlist_create_operation_payload_data_attributes;
pub use self::playlist_create_operation_payload_data_attributes::CreatePlaylistAttributes;
mod playlist_update_operation_payload_data_attributes;
pub use self::playlist_update_operation_payload_data_attributes::PlaylistUpdateOperationPayloadDataAttributes;
mod playlists_items_resource_identifier;
pub use self::playlists_items_resource_identifier::PlaylistsItemsResourceIdentifier;
mod playlists_items_resource_identifier_meta;
pub use self::playlists_items_resource_identifier_meta::PlaylistsItemsResourceIdentifierMeta;
mod playlists_relationships;
pub use self::playlists_relationships::PlaylistsRelationships;
mod playlist;
pub use self::playlist::{Playlist, PlaylistAttributes};
mod provider;
pub use self::provider::{Provider, ProviderAttributes};
mod resource_object_object_object;
pub use self::resource_object_object_object::ResourceObjectObjectObject;
mod search_results_relationships;
pub use self::search_results_relationships::SearchResultsRelationships;
mod search_result;
pub use self::search_result::{SearchResult, SearchResultAttributes};
mod search_suggestions_highlights;
pub use self::search_suggestions_highlights::SearchSuggestionsHighlights;
mod search_suggestions_history;
pub use self::search_suggestions_history::SearchSuggestionsHistory;
mod search_suggestions_relationships;
pub use self::search_suggestions_relationships::SearchSuggestionsRelationships;
mod search_suggestion;
pub use self::search_suggestion::{SearchSuggestion, SearchSuggestionAttributes};
mod search_suggestions_suggestions;
pub use self::search_suggestions_suggestions::SearchSuggestionsSuggestions;
mod track_file;
pub use self::track_file::{TrackFile, TrackFileAttributes};
mod track_manifest;
pub use self::track_manifest::{TrackManifest, TrackManifestAttributes};
mod track_source_files_relationships;
pub use self::track_source_files_relationships::TrackSourceFilesRelationships;
mod track_source_file;
pub use self::track_source_file::{TrackSourceFile, TrackSourceFileAttributes};
mod track_statistics_relationships;
pub use self::track_statistics_relationships::TrackStatisticsRelationships;
mod track_statistics;
pub use self::track_statistics::{TrackStatistics, TrackStatisticsAttributes};
mod tracks_relationships;
pub use self::tracks_relationships::TracksRelationships;
mod track;
pub use self::track::{Track, TrackAttributes};
mod user_collections_relationships;
pub use self::user_collections_relationships::UserCollectionsRelationships;
mod user_collection;
pub use self::user_collection::UserCollection;
mod user_entitlement;
pub use self::user_entitlement::{UserEntitlement, UserEntitlementAttributes};
mod user_recommendations_relationships;
pub use self::user_recommendations_relationships::UserRecommendationsRelationships;
mod user_recommendation;
pub use self::user_recommendation::UserRecommendation;
mod user_shares_relationships;
pub use self::user_shares_relationships::UserSharesRelationships;
mod user_share;
pub use self::user_share::{UserShare, UserShareAttributes};
mod user;
pub use self::user::{User, UserAttributes};
mod videos_relationships;
pub use self::videos_relationships::VideosRelationships;
mod video;
pub use self::video::{Video, VideoAttributes};

mod resource;
pub use resource::*;
