pub mod album;
pub mod artist;
pub mod artist_biography;
pub mod artist_role;
pub mod artwork_file;
pub mod artwork;
pub mod audio;
pub mod barcode_id;
pub mod copyright;
pub mod drm_data;
mod error_object;
pub use self::error_object::*;
mod error_object_source;
pub use self::error_object_source::*;
mod errors_document;
pub use self::errors_document::*;
mod external_link;
pub use self::external_link::*;
pub mod genre;
mod links; 
pub use self::links::*;
pub mod lyrics;
pub mod playlist;
pub mod provider;

/// Uncategorized models
mod search_results_relationships;
pub use self::search_results_relationships::SearchResultsRelationships;
mod search_result;
pub use self::search_result::{SearchResult, SearchResultAttributes};
mod search_suggestions_highlights;
pub use self::search_suggestions_highlights::SearchSuggestionsHighlights;
mod search_suggestions_history;
pub use self::search_suggestions_history::SearchSuggestionsHistory;
mod search_suggestions_relationships;
pub use self::search_suggestions_relationships::SearchSuggestionsRelationships;
mod search_suggestion;
pub use self::search_suggestion::{SearchSuggestion, SearchSuggestionAttributes};
mod search_suggestions_suggestions;
pub use self::search_suggestions_suggestions::SearchSuggestionsSuggestions;
mod track_file;
pub use self::track_file::{TrackFile, TrackFileAttributes};
mod track_manifest;
pub use self::track_manifest::{TrackManifest, TrackManifestAttributes};
mod track_statistics_relationships;
pub use self::track_statistics_relationships::TrackStatisticsRelationships;
mod track_statistics;
pub use self::track_statistics::{TrackStatistics, TrackStatisticsAttributes};
mod tracks_relationships;
pub use self::tracks_relationships::TracksRelationships;
mod track;
pub use self::track::{Track, TrackAttributes};
mod user_collections_relationships;
pub use self::user_collections_relationships::UserCollectionsRelationships;
mod user_collection;
pub use self::user_collection::UserCollection;
mod user_recommendations_relationships;
pub use self::user_recommendations_relationships::UserRecommendationsRelationships;
mod user_recommendation;
pub use self::user_recommendation::UserRecommendation;
mod user_shares_relationships;
pub use self::user_shares_relationships::UserSharesRelationships;
mod user_share;
pub use self::user_share::{UserShare, UserShareAttributes};
mod user;
pub use self::user::{User, UserAttributes};
mod video;
pub use self::video::{Video, VideoAttributes, VideoRelationships};

mod resource;
pub use resource::*;
