/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaylistItemsRelationshipAddOperationPayloadMeta {
    #[serde(rename = "positionBefore")]
    pub position_before: String,
}

impl PlaylistItemsRelationshipAddOperationPayloadMeta {
    pub fn new(position_before: String) -> PlaylistItemsRelationshipAddOperationPayloadMeta {
        PlaylistItemsRelationshipAddOperationPayloadMeta {
            position_before,
        }
    }
}

