/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaylistRelationships {
    #[serde(rename = "coverArt")]
    pub cover_art: MultiRelationship<ResourceIdentifier>,
    #[serde(rename = "items")]
    pub items: MultiRelationship<ResourceIdentifier<PlaylistsItemsIdentifierMeta>>,
    #[serde(rename = "owners")]
    pub owners: MultiRelationship<ResourceIdentifier>,
}

impl PlaylistRelationships {
    pub fn new(
        cover_art: MultiRelationship<ResourceIdentifier>,
        items: MultiRelationship<ResourceIdentifier<PlaylistsItemsIdentifierMeta>>,
        owners: MultiRelationship<ResourceIdentifier>,
    ) -> PlaylistRelationships {
        PlaylistRelationships {
            cover_art,
            items,
            owners,
        }
    }
}
