/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaylistCreateOperationPayload {
    #[serde(rename = "data")]
    pub data: models::PlaylistCreateOperationPayloadData,
}

impl PlaylistCreateOperationPayload {
    pub fn new(data: models::PlaylistCreateOperationPayloadData) -> PlaylistCreateOperationPayload {
        PlaylistCreateOperationPayload {
            data,
        }
    }
}

