/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaylistItemsRelationshipReorderOperationPayloadData {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "meta")]
    pub meta: models::PlaylistItemsRelationshipReorderOperationPayloadDataMeta,
    /// Resource type - Must be [`models::ResourceType::Tracks`] or [`models::ResourceType::Videos`]
    #[serde(rename = "type")]
    pub r#type: models::ResourceType,
}

impl PlaylistItemsRelationshipReorderOperationPayloadData {
    pub fn new(
        id: String,
        meta: models::PlaylistItemsRelationshipReorderOperationPayloadDataMeta,
        r#type: models::ResourceType,
    ) -> PlaylistItemsRelationshipReorderOperationPayloadData {
        match r#type {
            models::ResourceType::Tracks | models::ResourceType::Videos => {}
            _ => panic!(
                "Invalid resource type for playlist items: {:?}. Must be Tracks or Videos.",
                r#type
            ),
        }
        PlaylistItemsRelationshipReorderOperationPayloadData { id, meta, r#type }
    }
}
