/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchSuggestionsHighlights {
    #[serde(rename = "length")]
    pub length: i32,
    #[serde(rename = "start")]
    pub start: i32,
}

impl SearchSuggestionsHighlights {
    pub fn new(length: i32, start: i32) -> SearchSuggestionsHighlights {
        SearchSuggestionsHighlights {
            length,
            start,
        }
    }
}

