/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrackManifestsAttributes {
    #[serde(
        rename = "albumAudioNormalizationData",
        skip_serializing_if = "Option::is_none"
    )]
    pub album_audio_normalization_data: Option<models::AudioNormalizationData>,
    #[serde(rename = "drmData", skip_serializing_if = "Option::is_none")]
    pub drm_data: Option<models::DrmData>,
    /// Formats present in manifest
    #[serde(rename = "formats", skip_serializing_if = "Option::is_none")]
    pub formats: Option<Vec<FormatsFalse>>,
    /// Unique manifest hash
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    #[serde(
        rename = "trackAudioNormalizationData",
        skip_serializing_if = "Option::is_none"
    )]
    pub track_audio_normalization_data: Option<models::AudioNormalizationData>,
    /// Track presentation
    #[serde(rename = "trackPresentation", skip_serializing_if = "Option::is_none")]
    pub track_presentation: Option<TrackPresentationFalse>,
    /// Manifest URI
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
}

impl TrackManifestsAttributes {
    pub fn new() -> TrackManifestsAttributes {
        TrackManifestsAttributes {
            album_audio_normalization_data: None,
            drm_data: None,
            formats: None,
            hash: None,
            track_audio_normalization_data: None,
            track_presentation: None,
            uri: None,
        }
    }
}
/// Formats present in manifest
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FormatsFalse {
    #[serde(rename = "HEAACV1")]
    Heaacv1,
    #[serde(rename = "AACLC")]
    Aaclc,
    #[serde(rename = "FLAC")]
    Flac,
    #[serde(rename = "FLAC_HIRES")]
    FlacHires,
}

impl Default for FormatsFalse {
    fn default() -> FormatsFalse {
        Self::Heaacv1
    }
}
/// Track presentation
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TrackPresentationFalse {
    #[serde(rename = "FULL")]
    Full,
    #[serde(rename = "PREVIEW")]
    Preview,
}

impl Default for TrackPresentationFalse {
    fn default() -> TrackPresentationFalse {
        Self::Full
    }
}
