/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrackCreateOperationPayloadData {
    #[serde(rename = "attributes")]
    pub attributes: models::TrackCreateOperationPayloadDataAttributes,
    #[serde(rename = "relationships")]
    pub relationships: models::TrackCreateOperationPayloadDataRelationships,
    #[serde(rename = "type")]
    pub r#type: TypeFalse,
}

impl TrackCreateOperationPayloadData {
    pub fn new(
        attributes: models::TrackCreateOperationPayloadDataAttributes,
        relationships: models::TrackCreateOperationPayloadDataRelationships,
        r#type: TypeFalse,
    ) -> TrackCreateOperationPayloadData {
        TrackCreateOperationPayloadData {
            attributes,
            relationships,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeFalse {
    #[serde(rename = "tracks")]
    Tracks,
}

impl Default for TypeFalse {
    fn default() -> TypeFalse {
        Self::Tracks
    }
}
