/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TracksRelationships {
    #[serde(rename = "albums")]
    pub albums: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "artists")]
    pub artists: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "genres")]
    pub genres: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "lyrics")]
    pub lyrics: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "owners")]
    pub owners: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "providers")]
    pub providers: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "radio")]
    pub radio: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "similarTracks")]
    pub similar_tracks: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "sourceFile")]
    pub source_file: models::Relationship,
    #[serde(rename = "trackStatistics")]
    pub track_statistics: models::Relationship,
}

impl TracksRelationships {
    pub fn new(
        albums: models::MultiRelationship<models::ResourceIdentifier>,
        artists: models::MultiRelationship<models::ResourceIdentifier>,
        genres: models::MultiRelationship<models::ResourceIdentifier>,
        lyrics: models::MultiRelationship<models::ResourceIdentifier>,
        owners: models::MultiRelationship<models::ResourceIdentifier>,
        providers: models::MultiRelationship<models::ResourceIdentifier>,
        radio: models::MultiRelationship<models::ResourceIdentifier>,
        similar_tracks: models::MultiRelationship<models::ResourceIdentifier>,
        source_file: models::Relationship,
        track_statistics: models::Relationship,
    ) -> TracksRelationships {
        TracksRelationships {
            albums,
            artists,
            genres,
            lyrics,
            owners,
            providers,
            radio,
            similar_tracks,
            source_file,
            track_statistics,
        }
    }
}
