/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrackCreateOperationPayloadDataAttributes {
    /// Access type
    #[serde(rename = "accessType")]
    pub access_type: AccessTypeFalse,
    /// Explicit content
    #[serde(rename = "explicit", skip_serializing_if = "Option::is_none")]
    pub explicit: Option<bool>,
    #[serde(rename = "title")]
    pub title: String,
}

impl TrackCreateOperationPayloadDataAttributes {
    pub fn new(
        access_type: AccessTypeFalse,
        title: String,
    ) -> TrackCreateOperationPayloadDataAttributes {
        TrackCreateOperationPayloadDataAttributes {
            access_type,
            explicit: None,
            title,
        }
    }
}
/// Access type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccessTypeFalse {
    #[serde(rename = "PUBLIC")]
    Public,
    #[serde(rename = "UNLISTED")]
    Unlisted,
    #[serde(rename = "PRIVATE")]
    Private,
}

impl Default for AccessTypeFalse {
    fn default() -> AccessTypeFalse {
        Self::Public
    }
}
