/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrackFilesAttributes {
    #[serde(
        rename = "albumAudioNormalizationData",
        skip_serializing_if = "Option::is_none"
    )]
    pub album_audio_normalization_data: Option<models::AudioNormalizationData>,
    /// File's audio format
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<FormatFalse>,
    #[serde(
        rename = "trackAudioNormalizationData",
        skip_serializing_if = "Option::is_none"
    )]
    pub track_audio_normalization_data: Option<models::AudioNormalizationData>,
    /// Track presentation
    #[serde(rename = "trackPresentation", skip_serializing_if = "Option::is_none")]
    pub track_presentation: Option<TrackPresentationFalse>,
    /// File URL
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl TrackFilesAttributes {
    pub fn new() -> TrackFilesAttributes {
        TrackFilesAttributes {
            album_audio_normalization_data: None,
            format: None,
            track_audio_normalization_data: None,
            track_presentation: None,
            url: None,
        }
    }
}
/// File's audio format
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FormatFalse {
    #[serde(rename = "HEAACV1")]
    Heaacv1,
    #[serde(rename = "AACLC")]
    Aaclc,
    #[serde(rename = "FLAC")]
    Flac,
    #[serde(rename = "FLAC_HIRES")]
    FlacHires,
}

impl Default for FormatFalse {
    fn default() -> FormatFalse {
        Self::Heaacv1
    }
}
/// Track presentation
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TrackPresentationFalse {
    #[serde(rename = "FULL")]
    Full,
    #[serde(rename = "PREVIEW")]
    Preview,
}

impl Default for TrackPresentationFalse {
    fn default() -> TrackPresentationFalse {
        Self::Full
    }
}
