/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrackSourceFileCreateOperationPayloadDataRelationships {
    #[serde(rename = "track")]
    pub track: models::AttachSourceFileToTrack,
}

impl TrackSourceFileCreateOperationPayloadDataRelationships {
    pub fn new(
        track: models::AttachSourceFileToTrack,
    ) -> TrackSourceFileCreateOperationPayloadDataRelationships {
        TrackSourceFileCreateOperationPayloadDataRelationships { track }
    }
}
