/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TracksRelationships {
    #[serde(rename = "albums")]
    pub albums: models::MultiRelationshipDataDocument,
    #[serde(rename = "artists")]
    pub artists: models::MultiRelationshipDataDocument,
    #[serde(rename = "genres")]
    pub genres: models::MultiRelationshipDataDocument,
    #[serde(rename = "lyrics")]
    pub lyrics: models::MultiRelationshipDataDocument,
    #[serde(rename = "owners")]
    pub owners: models::MultiRelationshipDataDocument,
    #[serde(rename = "providers")]
    pub providers: models::MultiRelationshipDataDocument,
    #[serde(rename = "radio")]
    pub radio: models::MultiRelationshipDataDocument,
    #[serde(rename = "similarTracks")]
    pub similar_tracks: models::MultiRelationshipDataDocument,
    #[serde(rename = "sourceFile")]
    pub source_file: models::Relationship,
    #[serde(rename = "trackStatistics")]
    pub track_statistics: models::Relationship,
}

impl TracksRelationships {
    pub fn new(
        albums: models::MultiRelationshipDataDocument,
        artists: models::MultiRelationshipDataDocument,
        genres: models::MultiRelationshipDataDocument,
        lyrics: models::MultiRelationshipDataDocument,
        owners: models::MultiRelationshipDataDocument,
        providers: models::MultiRelationshipDataDocument,
        radio: models::MultiRelationshipDataDocument,
        similar_tracks: models::MultiRelationshipDataDocument,
        source_file: models::Relationship,
        track_statistics: models::Relationship,
    ) -> TracksRelationships {
        TracksRelationships {
            albums,
            artists,
            genres,
            lyrics,
            owners,
            providers,
            radio,
            similar_tracks,
            source_file,
            track_statistics,
        }
    }
}
