/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCollectionsRelationships {
    #[serde(rename = "albums")]
    pub albums: models::MultiRelationship<
        models::ResourceIdentifier<crate::apis::user_collections_api::UserCollectionsResourceMeta>,
    >,
    #[serde(rename = "artists")]
    pub artists: models::MultiRelationship<
        models::ResourceIdentifier<crate::apis::user_collections_api::UserCollectionsResourceMeta>,
    >,
    #[serde(rename = "owners")]
    pub owners: models::MultiRelationship<models::ResourceIdentifier>,
    #[serde(rename = "playlists")]
    pub playlists: models::MultiRelationship<
        models::ResourceIdentifier<crate::apis::user_collections_api::UserCollectionsResourceMeta>,
    >,
    #[serde(rename = "tracks")]
    pub tracks: models::MultiRelationship<
        models::ResourceIdentifier<crate::apis::user_collections_api::UserCollectionsResourceMeta>,
    >,
    #[serde(rename = "videos")]
    pub videos: models::MultiRelationship<
        models::ResourceIdentifier<crate::apis::user_collections_api::UserCollectionsResourceMeta>,
    >,
}

impl UserCollectionsRelationships {
    pub fn new(
        albums: models::MultiRelationship<
            models::ResourceIdentifier<
                crate::apis::user_collections_api::UserCollectionsResourceMeta,
            >,
        >,
        artists: models::MultiRelationship<
            models::ResourceIdentifier<
                crate::apis::user_collections_api::UserCollectionsResourceMeta,
            >,
        >,
        owners: models::MultiRelationship<models::ResourceIdentifier>,
        playlists: models::MultiRelationship<
            models::ResourceIdentifier<
                crate::apis::user_collections_api::UserCollectionsResourceMeta,
            >,
        >,
        tracks: models::MultiRelationship<
            models::ResourceIdentifier<
                crate::apis::user_collections_api::UserCollectionsResourceMeta,
            >,
        >,
        videos: models::MultiRelationship<
            models::ResourceIdentifier<
                crate::apis::user_collections_api::UserCollectionsResourceMeta,
            >,
        >,
    ) -> UserCollectionsRelationships {
        UserCollectionsRelationships {
            albums,
            artists,
            owners,
            playlists,
            tracks,
            videos,
        }
    }
}
