/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCollectionAlbumsRelationshipAddOperationPayloadData {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: TypeFalse,
}

impl UserCollectionAlbumsRelationshipAddOperationPayloadData {
    pub fn new(
        id: String,
        r#type: TypeFalse,
    ) -> UserCollectionAlbumsRelationshipAddOperationPayloadData {
        UserCollectionAlbumsRelationshipAddOperationPayloadData { id, r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeFalse {
    #[serde(rename = "albums")]
    Albums,
}

impl Default for TypeFalse {
    fn default() -> TypeFalse {
        Self::Albums
    }
}
