/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCollectionTracksRelationshipAddOperationPayloadData {
    #[serde(rename = "id")]
    pub id: String,
    /// Resource type - Must be [`models::ResourceType::Tracks`]
    #[serde(rename = "type")]
    pub r#type: models::ResourceType,
}

impl UserCollectionTracksRelationshipAddOperationPayloadData {
    pub fn new(id: String) -> UserCollectionTracksRelationshipAddOperationPayloadData {
        UserCollectionTracksRelationshipAddOperationPayloadData {
            id,
            r#type: models::ResourceType::Tracks,
        }
    }
}
