/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSharesRelationships {
    #[serde(rename = "owners")]
    pub owners: models::MultiRelationshipDataDocument,
    #[serde(rename = "sharedResources")]
    pub shared_resources: models::MultiRelationshipDataDocument,
}

impl UserSharesRelationships {
    pub fn new(owners: models::MultiRelationshipDataDocument, shared_resources: models::MultiRelationshipDataDocument) -> UserSharesRelationships {
        UserSharesRelationships {
            owners,
            shared_resources,
        }
    }
}

