/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCollectionVideosRelationshipRemoveOperationPayloadData {
    #[serde(rename = "id")]
    pub id: String,
    /// Resource type - accepts any valid resource type
    #[serde(rename = "type")]
    pub r#type: models::ResourceType,
}

impl UserCollectionVideosRelationshipRemoveOperationPayloadData {
    pub fn new(
        id: String,
        r#type: models::ResourceType,
    ) -> UserCollectionVideosRelationshipRemoveOperationPayloadData {
        UserCollectionVideosRelationshipRemoveOperationPayloadData { id, r#type }
    }
}
