/*
 * TIDAL API - Beta
 *
 * TIDAL API is a [JSON:API](https://jsonapi.org/) Web API that gives access to TIDAL functionality and data.
 *
 * The version of the OpenAPI document: 0.1.76
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserEntitlementsAttributes {
    /// entitlements for user
    #[serde(rename = "entitlements")]
    pub entitlements: Vec<EntitlementsFalse>,
}

impl UserEntitlementsAttributes {
    pub fn new(entitlements: Vec<EntitlementsFalse>) -> UserEntitlementsAttributes {
        UserEntitlementsAttributes { entitlements }
    }
}
/// entitlements for user
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EntitlementsFalse {
    #[serde(rename = "MUSIC")]
    Music,
    #[serde(rename = "DJ")]
    Dj,
}

impl Default for EntitlementsFalse {
    fn default() -> EntitlementsFalse {
        Self::Music
    }
}
